env:
  APP_REPO: "buildkite-file-change-source"
  DOCS_REPO: "buildkite-file-change-destination"

steps:
- label: "Push updated OpenAPI spec to docs site"
  if: build.branch == 'main'
  command: |
    cp openapi.json $DOCS_REPO/openapi.json
    cd $DOCS_REPO
    git config --local user.email "buildkite-tyler@auerbeck.dev"
    git config --local user.name "buildkite-tyler"
    git checkout -b buildkite-openapi-$BUILDKITE_BUILD_NUMBER
    git add .
    git commit -m "[buildkite] bump openapi"
    git push origin buildkite-openapi-$BUILDKITE_BUILD_NUMBER
    # hub pull-request -m "[buildkite] bump openapi spec" --no-edit 
  plugins:
    - equinixmetal-buildkite/git-clone:
        repository: git@github.com:auerbecklabs/$DOCS_REPO.git
    - envato/github-pull-request#v0.4.0:
        title: "[buildkite] bump image tag to $BUILDKITE_COMMIT"
        head: buildkite-openapi-$BUILDKITE_BUILD_NUMBER
        base: main
    # - jcouyang/hub#1.0:
    #    os: 'linux'
