steps:

- label: "Check OpenAPI Spec"
  if: build.branch == 'main'
  plugins:
    - monebag/monorepo-diff#v2.5.9:
        diff: "git diff --name-only HEAD~1"
        watch:
          - path: "openapi.json"
            label: "Publish OpenAPI Spec"
            config:
              command: "buildkite-agent pipeline upload .buildkite/openapi.yaml"
